create database Address_Book_Service;
use Address_Book_Service;
show databases;
select database();
show tables;
create table Address_Book(id int primary key auto_increment, firstname varchar(20), lastname varchar(20), address varchar(60), city varchar(20), state varchar(30), zip int, phone_no long, email varchar(160)); 
describe address_book;
insert into address_book(firstname, lastname, address, city, state, zip, phone_no, email) values ('Rehan', 'Shaikh', 'Garden', 'Mumbra', 'Maha', 400612, 7738565536, 're@gmail.com'),('Zaid','Shaikh','Wadi','Mumbai','Maha',4000003, 9819585533, 'zd@gmail.com');
select * from address_book;
update address_book set lastname = 'Khan' where firstname = 'Zaid';
insert into address_book(firstname, lastname, address, city, state, zip, phone_no, email) values ('Alina', 'Sayed', 'Nagar', 'Mumbai', 'Maha', 400112, 7738565536, 'rsm@gmail.com');
delete from address_book where firstname = 'Alina';
select firstname, lastname, address, city, state, zip, phone_no, email from address_book where city = 'Mumbra';
select firstname, lastname, address, city, state, zip, phone_no, email from address_book where state = 'maha';
select city , count(city) from address_book group by city;
select state , count(state) from address_book group by state;
select * from address_book where city = 'Mumbai' order by firstname;
alter table address_book add type varchar(50);
alter table address_book rename to My_Book;
describe My_Book;
update my_book set type = 'Family' where firstname = 'Rehan';
select * from my_book;
update my_book set type = 'Family' where firstname = 'Zaid';
update my_book set type = 'Profession' where firstname = 'Alina';
select type , count(type) from my_book group by type;